export enum OrderStatus {
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
  CANCELADO = 'CANCELADO',
  RECEBIDO = 'RECEBIDO',
  PREPARANDO = 'PREPARANDO',
  PRONTO = 'PRONTO',
  FINALIZADO = 'FINALIZADO',
}
